# GET http://localhost:3001/api/persons/60d0c26ac6974d40ac2c8e50

POST http://localhost:3001/api/persons
Content-Type : application/json

{
    "name": "",
    "number": "9887723114"
}

# DELETE http://localhost:3001/persons/4